target-version = "py310"

line-length = 90

include = [
    "python/**.py",
    "python/**.pyi",
    "tests/**.py",
    "benchmark/run.py",
]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
no-lines-before = ["local-folder"]
extra-standard-library = ["tomllib"]

[lint]
preview = true

select = ["ALL"]
ignore = [
    "D",
    "DOC",
    "CPY001",
    #______#
    "PLR2004",
    "PLR6201",
    #______#
    "ANN401",
    #______#
    "ARG001",
    "ARG002",
]

[lint.per-file-ignores]
"benchmark/run.py" = [
    "INP001",
]
"tests/**.py" = [
    "S101",
]

[lint.mccabe]
# https://docs.astral.sh/ruff/settings/#lint_mccabe_max-complexity
max-complexity = 15

[lint.pycodestyle]
# E501 reports lines that exceed the length of 100.
max-line-length = 320