[package]
name = "toml-rs"
version = "0.3.1"
edition = "2024"
license = "Unlicense"
repository = "https://github.com/lava-sh/toml-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_toml_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.0", features = [
    "extension-module",
    "generate-import-lib",
    "num-bigint",
] }
num-bigint = "0.4.6"
rustc-hash = "2.1.1"
smallvec = "2.0.0-alpha.12"
memchr = { version = "2.8.0", default-features = false }
bytecount = { version = "0.6.9", features = ["runtime-dispatch-simd"] }

[dependencies.mimalloc]
optional = true
version = "0.1.48"
features = [
    # mimalloc v3
    # See: https://github.com/microsoft/mimalloc/tree/dev3?tab=readme-ov-file#branches
    "v3",
    "override",
    "local_dynamic_tls",
]

[dependencies.lexical-core]
git = "https://github.com/Alexhuszagh/rust-lexical"
rev = "59382e249f8fd0dd384ed1f180b38d168cf9fcbb"
default-features = false
features = [
    "radix",
    "parse-integers",
]

# TOML v1.0.0 support
[dependencies.toml_edit_v1]
git = "https://github.com/lava-sh/toml"
rev = "e2452d383bccf7f54d494b5a2e130772e037f1fc"
features = [
    "serde",
    "unbounded",
]

[dependencies.toml_v1]
git = "https://github.com/lava-sh/toml"
rev = "e2452d383bccf7f54d494b5a2e130772e037f1fc"
features = [
    "fast_hash", # uses `foldhash`
    "unbounded", # disables default recursion limit to set own limit (999)
    "preserve_order", # save order
]

# TOML v1.1.0 support
[dependencies.toml_edit]
git = "https://github.com/lava-sh/toml"
rev = "83f620f5d00a9b7801302a2a846c7f6ff7dc065b"
features = [
    "serde",
    "unbounded",
]

[dependencies.toml]
git = "https://github.com/lava-sh/toml"
rev = "83f620f5d00a9b7801302a2a846c7f6ff7dc065b"
features = [
    "fast_hash", # uses `foldhash`
    "unbounded", # disables default recursion limit to set own limit (999)
    "preserve_order", # save order
]

[features]
default = []
mimalloc = ["dep:mimalloc"]

[profile.release]
lto = "fat"
strip = "symbols"
codegen-units = 1

[lints]
rust.warnings = { level = "deny" }
clippy.perf = { level = "deny", priority = -1 }
clippy.style = { level = "warn", priority = -1 }
clippy.pedantic = { level = "warn", priority = -1 }

clippy.let_and_return = "allow" # sometimes good to name what you are returning
clippy.too_many_lines = "allow"
clippy.similar_names = "allow"
