[package]
name = "toml-rs"
edition = "2024"
license = "Unlicense"
repository = "https://github.com/lava-sh/toml-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "_toml_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.27.1", features = [
    "nightly",
    "extension-module",
    "generate-import-lib",
] }
toml = { version = "0.9.8", features = [
    "fast_hash", # uses `foldhash`
    "unbounded", # disables default recursion limit to set own limit (999)
    "preserve_order", # save order
] }
toml_edit = { version = "0.23.7", features = [
    "serde",
    "unbounded",
] }
rustc-hash = "2.1.1"
smallvec = "2.0.0-alpha.12"
memchr = { version = "2.7.6", default-features = false }

[dependencies.lexical-core]
git = "https://github.com/Alexhuszagh/rust-lexical"
rev = "59382e249f8fd0dd384ed1f180b38d168cf9fcbb"
default-features = false
features = ["write-floats"]

[dependencies.mimalloc]
version = "*"
features = ["v3"]
optional = true

[features]
default = ["dep:mimalloc"]

[profile.release]
lto = "fat"
strip = "symbols"
codegen-units = 1